
include $(TOPDIR)/config.mk

LIB	:= $(obj)libamlnf_phy.o


$(obj)/libamlnf_phy.o:
	@cp ./libamlnf_phy_131112.z ../../../build/drivers/amlnf/phy/libamlnf_phy.o

#########################################################################

include $(SRCTREE)/rules.mk

sinclude $(obj).depend

#########################################################################
