#ifndef __CONFIG_M6_MBX_V1_TEE_H__
#define __CONFIG_M6_MBX_V1_TEE_H__

#include "m6_mbx_v1.h"

#undef CONFIG_IMPROVE_UCL_DEC
#undef CONFIG_ENV_IN_SPI_OFFSET
#undef CONFIG_ENV_SIZE
#define CONFIG_ENV_IN_SPI_OFFSET	0x100000
#define CONFIG_ENV_SIZE			0x10000

/*
 * Secure OS
 */
#define CONFIG_MESON_TRUSTZONE 1

#ifdef CONFIG_MESON_TRUSTZONE
//#define CONFIG_MESON_SECUREARGS  1
#define CONFIG_JOIN_UBOOT_SECUREOS 1
#define SECUREOS_KEY_BASE_ADDR 0xa0000000
#define SECURE_OS_DECOMPRESS_ADDR 0xa0100000
#define CONFIG_SECURE_STORAGE_BURNED
#ifdef CONFIG_SECURE_STORAGE_BURNED
#define CONFIG_MESON_STORAGE_BURN 1
#define CONFIG_MESON_STORAGE_DEBUG
#define CONFIG_SECURESTORAGEKEY
#define CONFIG_RANDOM_GENERATE
#define CONFIG_CMD_SECURESTORE
#define CONFIG_CMD_RANDOM
/* secure storage support both spi and emmc */
#define CONFIG_SECURE_MMC
#define CONFIG_SPI_NOR_SECURE_STORAGE
#endif

#endif //CONFIG_MESON_TRUSTZONE

#endif //__CONFIG_M6_MBX_V1_TEE_H__
