#ifndef __CONFIG_M8_K200_V1_TEE_H__
#define __CONFIG_M8_K200_V1_TEE_H__

#include "m8_k200_v1.h"

/*
 * Secure OS
 */
#define CONFIG_MESON_TRUSTZONE 1

#ifdef CONFIG_MESON_TRUSTZONE
//#define CONFIG_MESON_SECUREARGS  1
#define CONFIG_JOIN_UBOOT_SECUREOS 1
#define SECUREOS_KEY_BASE_ADDR 0x06100000
#define SECURE_OS_DECOMPRESS_ADDR 0x06200000
#define CONFIG_SECURE_STORAGE_BURNED
#ifdef CONFIG_SECURE_STORAGE_BURNED
#define CONFIG_MESON_STORAGE_BURN 1
#define CONFIG_MESON_STORAGE_DEBUG
#define CONFIG_SECURESTORAGEKEY
#define CONFIG_RANDOM_GENERATE
#define CONFIG_CMD_SECURESTORE
#define CONFIG_CMD_RANDOM
/* secure storage support both spi and emmc */
#define CONFIG_SECURE_MMC
#define CONFIG_SPI_NOR_SECURE_STORAGE
#endif

#endif //CONFIG_MESON_TRUSTZONE

#endif //__CONFIG_M8_K200_V1_TEE_H__
